name: Car_service
description: Functional Flutter Starter Kit
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  cloud_functions: ^4.0.5
  intl:
  lottie: ^1.1.0
  emoji_picker_flutter:


  shared_preferences: ^2.0.15
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^5.0.6
  http: ^0.13.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_svg: ^1.1.6
  rate_my_app: ^1.1.3
  dio: ^4.0.6
  firebase_database: ^10.0.6
  geolocator: ^9.0.2
  tracking: ^0.0.1
  google_fonts: ^2.0.0
  fl_chart: ^0.35.0
  google_sign_in: ^5.4.2
  bottom_sheet: ^3.1.2
  flutter_phone_direct_caller: ^2.1.1
  provider: ^6.0.2
  flutter_easyloading: ^3.0.3
  firebase_app_check: ^0.1.1+6
  data_table_2: ^2.0.3
  flutter_spinkit:
  fluttertoast:
  font_awesome_flutter:
  carousel_slider:
  floating_action_bubble:
  flutter_rating_bar: ^4.0.1
  image_picker_for_web: ^2.1.6
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.4.1
  percent_indicator: ^4.2.2
  animations: ^2.0.0
  image: ^3.0.2
  path_provider: ^2.0.2
  geocoding: ^2.0.0
  timeago: ^3.1.0
  image_cropper: ^3.0.0
  ionicons: ^0.2.1
  loading_overlay: ^0.3.0
  like_button: ^2.0.4
  flutter_chat_bubble: ^2.0.0
  permission_handler: ^10.1.0
  story: ^0.8.0
  story_view: ^0.14.0
  custom_navigation_bar:
  eva_icons_flutter:
  page_transition:
  pull_to_refresh:
  flutter_launcher_icons:
  line_icons:
  dotted_border:






  flare_flutter:
  transparent_image:
  time_machine:
  flutter_slidable:
  flutter_secure_storage:
  firebase_messaging:

  characters:






  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png
  fonts:
    - family: myfont
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/admin.png
    - assets/icons/